version: '3.8'

services:
  php-apache:
    build: ./php
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - lamp-network
    container_name: php-apache

  db:
    image: mysql:5.7
    container_name: db

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myappdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lamp-network

  phpmyadmin:
    container_name: phpmyadmin

    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - lamp-network

networks:
  lamp-network:
    driver: bridge

volumes:
  db-data:
